{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "af2d3826",
   "metadata": {},
   "source": [
    "# Lego Tutorial\n",
    "\n",
    "I stumbled across a [question in the build123d FAQ](https://build123d.readthedocs.io/en/latest/tips.html#isnt-from-build123d-import-bad-practice) about using glob imports. I see how they make sense, but while I'm running through the tutorials, highlighting new classes and functions is useful."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "c2524a0f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import (\n",
    "    Align,\n",
    "    Axis,\n",
    "    Box,\n",
    "    BuildPart,\n",
    "    BuildSketch,\n",
    "    Circle,\n",
    "    Cylinder,\n",
    "    GridLocations,\n",
    "    Kind,\n",
    "    Locations,\n",
    "    Mode,\n",
    "    Rectangle,\n",
    "    extrude,\n",
    "    offset,\n",
    ")\n",
    "from ocp_vscode import show\n",
    "\n",
    "pip_count = 6\n",
    "\n",
    "lego_unit_size = 8\n",
    "pip_height = 1.8\n",
    "pip_diameter = 4.8\n",
    "block_length = lego_unit_size * pip_count\n",
    "block_width = 16\n",
    "base_height = 9.6\n",
    "block_height = base_height + pip_height\n",
    "support_outer_diameter = 6.5\n",
    "support_inner_diameter = 4.8\n",
    "ridge_width = 0.6\n",
    "ridge_depth = 0.3\n",
    "wall_thickness = 1.2\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "600fc882",
   "metadata": {},
   "source": [
    "A rectangle the right size for the Lego block."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1854cfd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-c"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "\n",
    "show(plan)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e516c57d",
   "metadata": {},
   "source": [
    "Turn the rectangle into the plan for the walls by using offset to give the edges a specific width."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f1187383",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "\n",
    "show(plan)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e96f65f5",
   "metadata": {},
   "source": [
    "Now we need to add the ridges on the bottom of the Lego piece. We'll start with a grid, created in two steps. First, the lengthwise bars."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c49e24ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        # First up, the lengthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        # with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "        #     Rectangle(width=ridge_width, height=block_width)\n",
    "\n",
    "show(plan)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5edc9237",
   "metadata": {},
   "source": [
    "Now we need to add the widthwise bars."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "684bb9c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "\n",
    "show(plan)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eea54880",
   "metadata": {},
   "source": [
    "Finally, to convert the grid into the ridges, we cut away a rectangle from the grid."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "dbd54797",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "        # Subtract a rectangle leaving ribs on the block walls\n",
    "        Rectangle(\n",
    "            block_length - 2 * (wall_thickness + ridge_depth),\n",
    "            block_width - 2 * (wall_thickness + ridge_depth),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "\n",
    "show(plan)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "063ed6e4",
   "metadata": {},
   "source": [
    "Now we have the ridges on the base, it's time to add the hollow cylinders - or hollow circles on the 2D plane."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "01d5c683",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "++\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "        # Subtract a rectangle leaving ribs on the block walls\n",
    "        Rectangle(\n",
    "            block_length - 2 * (wall_thickness + ridge_depth),\n",
    "            block_width - 2 * (wall_thickness + ridge_depth),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a row of hollow circles to the center\n",
    "        with GridLocations(\n",
    "            x_spacing=lego_unit_size, y_spacing=0, x_count=pip_count - 1, y_count=1\n",
    "        ):\n",
    "            Circle(radius=support_outer_diameter / 2)\n",
    "            Circle(radius=support_inner_diameter / 2, mode=Mode.SUBTRACT)\n",
    "\n",
    "show(plan)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e9e7342e",
   "metadata": {},
   "source": [
    "Time to go from 2D to 3D by extruding the Sketch object"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "03d5a059",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "        # Subtract a rectangle leaving ribs on the block walls\n",
    "        Rectangle(\n",
    "            block_length - 2 * (wall_thickness + ridge_depth),\n",
    "            block_width - 2 * (wall_thickness + ridge_depth),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a row of hollow circles to the center\n",
    "        with GridLocations(\n",
    "            x_spacing=lego_unit_size, y_spacing=0, x_count=pip_count - 1, y_count=1\n",
    "        ):\n",
    "            Circle(radius=support_outer_diameter / 2)\n",
    "            Circle(radius=support_inner_diameter / 2, mode=Mode.SUBTRACT)\n",
    "    # Extrude this base sketch to the height of the walls\n",
    "    extrude(amount=base_height - wall_thickness)\n",
    "\n",
    "show(lego)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "26707ac3",
   "metadata": {},
   "source": [
    "Now we add a lid using Box."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "c1859c20",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "        # Subtract a rectangle leaving ribs on the block walls\n",
    "        Rectangle(\n",
    "            block_length - 2 * (wall_thickness + ridge_depth),\n",
    "            block_width - 2 * (wall_thickness + ridge_depth),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a row of hollow circles to the center\n",
    "        with GridLocations(\n",
    "            x_spacing=lego_unit_size, y_spacing=0, x_count=pip_count - 1, y_count=1\n",
    "        ):\n",
    "            Circle(radius=support_outer_diameter / 2)\n",
    "            Circle(radius=support_inner_diameter / 2, mode=Mode.SUBTRACT)\n",
    "    # Extrude this base sketch to the height of the walls\n",
    "    extrude(amount=base_height - wall_thickness)\n",
    "\n",
    "    # Create a box on the top of the walls\n",
    "    with Locations((0, 0, lego.vertices().sort_by(Axis.Z)[-1].Z)):\n",
    "        # Create the top of the block\n",
    "        Box(\n",
    "            length=block_length,\n",
    "            width=block_width,\n",
    "            height=wall_thickness,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "        )\n",
    "\n",
    "show(lego)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "a32558bc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as lego:\n",
    "    # Draw the bottom of the block\n",
    "    with BuildSketch() as plan:\n",
    "        # Start with a Rectangle the size of the block\n",
    "        perimeter = Rectangle(width=block_length, height=block_width)\n",
    "        # Subtract an offset to create the block walls\n",
    "        offset(\n",
    "            perimeter,\n",
    "            -wall_thickness,\n",
    "            kind=Kind.INTERSECTION,\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a grid of lengthwise and widthwise bars\n",
    "        with GridLocations(x_spacing=0, y_spacing=lego_unit_size, x_count=1, y_count=2):\n",
    "            Rectangle(width=block_length, height=ridge_width)\n",
    "        with GridLocations(lego_unit_size, 0, pip_count, 1):\n",
    "            Rectangle(width=ridge_width, height=block_width)\n",
    "        # Subtract a rectangle leaving ribs on the block walls\n",
    "        Rectangle(\n",
    "            block_length - 2 * (wall_thickness + ridge_depth),\n",
    "            block_width - 2 * (wall_thickness + ridge_depth),\n",
    "            mode=Mode.SUBTRACT,\n",
    "        )\n",
    "        # Add a row of hollow circles to the center\n",
    "        with GridLocations(\n",
    "            x_spacing=lego_unit_size, y_spacing=0, x_count=pip_count - 1, y_count=1\n",
    "        ):\n",
    "            Circle(radius=support_outer_diameter / 2)\n",
    "            Circle(radius=support_inner_diameter / 2, mode=Mode.SUBTRACT)\n",
    "    # Extrude this base sketch to the height of the walls\n",
    "    extrude(amount=base_height - wall_thickness)\n",
    "\n",
    "    # Create a box on the top of the walls\n",
    "    with Locations((0, 0, lego.vertices().sort_by(Axis.Z)[-1].Z)):\n",
    "        # Create the top of the block\n",
    "        Box(\n",
    "            length=block_length,\n",
    "            width=block_width,\n",
    "            height=wall_thickness,\n",
    "            align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "        )\n",
    "\n",
    "    # Create a workplane on the top of the block\n",
    "    with BuildPart(lego.faces().sort_by(Axis.Z)[-1]):\n",
    "        # Create a grid of pips\n",
    "        with GridLocations(lego_unit_size, lego_unit_size, pip_count, 2):\n",
    "            Cylinder(\n",
    "                radius=pip_diameter / 2,\n",
    "                height=pip_height,\n",
    "                align=(Align.CENTER, Align.CENTER, Align.MIN),\n",
    "            )\n",
    "show(lego)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
