{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "3a1cdc63",
   "metadata": {},
   "source": [
    "Taken from the [build123d tutorial](https://build123d.readthedocs.io/en/latest/tutorial_selectors.html)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "58660837",
   "metadata": {},
   "outputs": [],
   "source": [
    "from build123d import (\n",
    "    Axis,\n",
    "    BuildPart,\n",
    "    BuildSketch,\n",
    "    Circle,\n",
    "    Cylinder,\n",
    "    RegularPolygon,\n",
    "    Mode,\n",
    "    extrude,\n",
    ")\n",
    "from ocp_vscode import show\n",
    "\n",
    "cylinder_radius = 10\n",
    "cylinder_height = 3\n",
    "hexagon_radius = 7\n",
    "hexagon_side_count = 6\n",
    "inner_circle_radius = 4\n",
    "cut_depth = 2\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9a7a0f04",
   "metadata": {},
   "source": [
    "Step 1. Create a lovely cylinder, which we'll then modify"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "faca74c6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as example:\n",
    "    Cylinder(\n",
    "        radius=cylinder_radius,\n",
    "        height=cylinder_height,\n",
    "    )\n",
    "\n",
    "show(example)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bbd415a8",
   "metadata": {},
   "source": [
    "Step 2. Create a hexagon with a hole cut in it\n",
    "1. Create a hexagon in a 2D sketch\n",
    "1. Add a circle inside the hexagon and subtract it from the hexagon"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "03b3f8f2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-c\n"
     ]
    }
   ],
   "source": [
    "with BuildSketch() as hexagon:\n",
    "    RegularPolygon(radius=hexagon_radius, side_count=hexagon_side_count)\n",
    "    Circle(radius=inner_circle_radius, mode=Mode.SUBTRACT)\n",
    "\n",
    "show(hexagon)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a79da1d6",
   "metadata": {},
   "source": [
    "Step 3. Use the hexagon shape from Step 2 to cut out the same shape from the cylinder in Step 1\n",
    "1. Select the top face (the highest face on the Z-axis) and add a 2D sketch to it\n",
    "1. Add the hexagonal doughnut from Step 2 to the sketch\n",
    "1. Use `extrude` with a negative value to cut the doughnut shape out of the cylinder"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "c2d50b06",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "with BuildPart() as example:\n",
    "    Cylinder(\n",
    "        radius=cylinder_radius,\n",
    "        height=cylinder_height,\n",
    "    )\n",
    "    with BuildSketch(example.faces().sort_by(Axis.Z)[-1]):\n",
    "        RegularPolygon(radius=hexagon_radius, side_count=hexagon_side_count)\n",
    "        Circle(radius=inner_circle_radius, mode=Mode.SUBTRACT)\n",
    "    extrude(amount=-cut_depth, mode=Mode.SUBTRACT)\n",
    "\n",
    "show(example)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
